name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    #strategy:
      #matrix:
        #compiler: [gcc, clang]
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          chmod +x install_env.sh
          sudo bash install_env.sh

      - name: Build project
        run: |
          make
          ls
          echo "build:"
          ls build

      - name: Run unit tests
        run: make unit_tests

      - name: Run e2e tests
        run: make e2e_tests

      - name: Run valgrind
        run: make valgrind

      - name: Run clang-tidy
        run: make clang_tidy
